---
seed_products:
  - repo: shared
    tag: v0.1.0-alpha
    public: true
  - repo: app-shared
    tag: v0.1.0-alpha
    public: true
  - repo: mitglieder-lokal
    tag: v0.4.0-alpha
    public: true
  - repo: finanz-rechner
    tag: v0.1.0-alpha
    public: true
  - repo: finanz-shared
    tag: v0.1.0-alpha
    public: true
  - repo: rechnung-lokal
    tag: v0.1.0-alpha
    public: true
